const cityData = [
  {
    id: 1,
    name: "Delhi",
    top: "18%",
    left: "56%",
    severity: "critical",
    disaster: "Flood",
    ai: 96,
    resources: 18,
  },
  {
    id: 2,
    name: "Mumbai",
    top: "45%",
    left: "36%",
    severity: "critical",
    disaster: "Rescue",
    ai: 91,
    resources: 15,
  },
  {
    id: 3,
    name: "Kolkata",
    top: "38%",
    left: "73%",
    severity: "warning",
    disaster: "Cyclone",
    ai: 93,
    resources: 20,
  },
  {
    id: 4,
    name: "Bengaluru",
    top: "69%",
    left: "50%",
    severity: "safe",
    disaster: "Medical",
    ai: 88,
    resources: 14,
  },
  {
    id: 5,
    name: "Chennai",
    top: "79%",
    left: "60%",
    severity: "warning",
    disaster: "Storm",
    ai: 90,
    resources: 16,
  },
];

export default cityData;